# Generated by Django 3.2.6 on 2021-08-04 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tgbase", "0001_initial"),
        ("tgbot", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trackedpythonpackage",
            name="user",
        ),
        migrations.AddField(
            model_name="trackedpythonpackage",
            name="chat",
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to="tgbase.chat"),
            preserve_default=False,
        ),
    ]
