# Generated by Django 3.2.6 on 2021-08-29 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [
        ("packages", "0001_initial"),
        ("packages", "0002_alter_pythonpackage_last_updated"),
        ("packages", "0003_alter_pythonpackage_last_updated"),
        ("packages", "0004_rustpackage"),
    ]

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PythonPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("last_version", models.CharField(blank=True, max_length=100, null=True)),
                ("last_prerelease", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated", models.DateTimeField(db_index=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RustPackage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("name", models.CharField(max_length=100, unique=True)),
                ("last_version", models.CharField(blank=True, max_length=100, null=True)),
                ("last_prerelease", models.CharField(blank=True, max_length=100, null=True)),
                ("last_updated", models.DateTimeField(db_index=True, null=True)),
                ("enabled", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
