# Generated by Django 3.2.6 on 2021-08-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("packages", "0001_squashed_0004_rustpackage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pythonpackage",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="pythonpackage",
            name="slug",
            field=models.SlugField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="rustpackage",
            name="name",
            field=models.CharField(max_length=127, unique=True),
        ),
        migrations.AlterField(
            model_name="rustpackage",
            name="slug",
            field=models.SlugField(max_length=127, unique=True),
        ),
    ]
