---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    x-app: backend-website
  name: backend-website
spec:
  replicas: 1
  selector:
    matchLabels:
      x-app: backend-website
  template:
    metadata:
      labels:
        x-app: backend-website
    spec:
      containers:
      - name: backend-website
        command: ["poetry", "run", "hypercorn", "--config", "hypercorn.toml", "project.asgi:application"]
        envFrom:
        - configMapRef:
            name: app-config
        image: {{ .Values.werf.image.backend }}
      restartPolicy: Always
      imagePullSecrets:
        - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  labels:
    x-app: backend-website
  name: backend-website
spec:
  ports:
  - name: "web"
    port: 8080
    targetPort: 8080
  selector:
    x-app: backend-website
---
apiVersion: batch/v1
kind: Job
metadata:
  name: db-migrate
  annotations:
    "helm.sh/hook": pre-install, pre-upgrade
    "helm.sh/hook-weight": "10"
spec:
  activeDeadlineSeconds: 60
  template:
    spec:
      restartPolicy: Never
      containers:
      - name: db-migrate
        envFrom:
        - configMapRef:
            name: app-config
        image: {{ .Values.werf.image.backend }}
        command: ["poetry", "run", "python", "manage.py", "migrate"]
      imagePullSecrets:
        - name: regcred
